version: "3.17"

tasks:

    run:
        deps: [build]
        cmds:
            - python dist/bundle.py

    dev:
        cmds:
            - pipenv run python scripts/dev.py -OO

    build:
        aliases: [dist]
        deps: [check]
        cmds:
            - defer: pipenv run python scripts/build.py -OO

    check:
        deps: [lint, format]

    format:
        cmds:
            - pipenv run ruff format --config pyproject.toml

    lint:
        cmds:
            - pipenv run ruff check --config pyproject.toml
    setup:
        cmds:
            - pipenv --quiet install
            - pipenv --quiet lock
