version: '3'

tasks:

    dev:
        cmds:
            - task format
            - pipenv run python src/__main__.py

    dist:
        cmds:
            - task build
            - python dist/bundle.py

    build:
        cmds:
            - task format
            - pipenv run python scripts/build.py

    format:
        cmds:
            - pipenv run ruff check --fix --config ruff.toml
            - pipenv run ruff format --config ruff.toml

    setup:
        cmds:
            - pipenv install
            - pipenv lock
            - pipenv run python scripts/setup.py

    background:
        watch: true
        sources: 
            - "./Pipfile"
        cmds:
            - pipenv run python scripts/setup.py