version: "3.17"

tasks:

    run:
        deps: [build]
        cmds:
            - uv run dist/bundle.pyz

    dev:
        cmds:
            - uv run efec dev

    build:
        aliases: [dist, bundle]
        deps: [check]
        cmds:
            - defer: uv run efec dist

    check:
        deps: [lint, format]

    format:
        cmds:
            - uv run ruff format --config pyproject.toml

    lint:
        cmds:
            - uv run ruff check --config pyproject.toml
    
    lock:
        cmds:
            - uv lock
            - uv sync

    setup:
        cmds:
            - uv venv --python 3.11
            - uv sync
            - uv lock
