version: "3.17"

tasks:

    run:
        deps: [build]
        cmds:
            - python dist/bundle.py

    dev:
        cmds:
            - pipenv run python scripts/dev.py -OO
            - task hmr -w

    hmr:
        watch: true
        cmds:
            - pipenv run python scripts/dev.py -OO
        sources:
            - src/**/**

    build:
        aliases: [dist]
        deps: [check]
        cmds:
            - defer: pipenv run python scripts/build.py

    check:
        deps: [lint, format]

    format:
        cmds:
            - pipenv run ruff format --config ruff.toml

    lint:
        cmds:
            - pipenv run ruff check --fix --config ruff.toml
            - pipenv run mypy src/

    setup:
        cmds:
            - pipenv --quiet install
            - pipenv --quiet lock
            - pipenv run mypy --install-types
