version: "3.17"

tasks:

    run:
        deps: [build]
        cmds:
            - uv run dist/bundle.py

    dev:
        cmds:
            - uv run scripts/dev.py -OO

    build:
        aliases: [dist]
        deps: [check]
        cmds:
            - defer: uv run scripts/build.py -OO

    check:
        deps: [lint, format]

    format:
        cmds:
            - uv run ruff format --config pyproject.toml

    lint:
        cmds:
            - uv run ruff check --config pyproject.toml
    setup:
        cmds:
            - uv venv --python 3.11
            - uv sync
            - uv lock
