version: '3'

tasks:

    run:
        deps: [build]
        cmds:
            - python dist/bundle.py

    dev:
        deps: [check]
        cmds:
            - pipenv run python src/__main__.py

    build:
        aliases: [dist]
        deps: [check]
        cmds:
            - defer: pipenv run python scripts/build.py

    check:
        deps: [lint, format]

    format:
        cmds:
            - pipenv run ruff format --config ruff.toml

    lint:
        cmds:
            - pipenv run ruff check --fix --config ruff.toml
            - pipenv run mypy src/

    setup:
        cmds:
            - pipenv --quiet install
            - task: cache
            - pipenv --quiet lock

    cache:
        cmds:
            - pipenv run python scripts/setup.py
            - pipenv run mypy --install-types

    background:
        watch: true
        deps: [cache]
        sources: 
            - "./Pipfile"